### ISSUE TITLE
Adding streamer with Chinese characters crashes the streamer list

### ISSUE THREAD

**Issue by OonceyDooncey** [Tyaaa-aa/Octo-Party-V2#1]
Tried adding in streamer Jazlatte "絕世拿鐵(jazlatte)" causes an error. Upon refreshing, the original list of streamers disappears.

**Comment by Tyaaa-aa** [comment]
The commit 8e45b1f09e70e7c2039304502b31aa5fc9125ac7 solved the issue @OonceyDooncey
