### ISSUE TITLE
[Feature Request] Close all streams button

### ISSUE THREAD

**Issue by darkcnight** [Tyaaa-aa/Octo-Party-V2#11]
As per title. Currently if you have remember last layout turned on you cannot close them all by refreshing so you'd have to turn off remember layout refresh then turn it back on if that's your desired setting. Close all streams solves this issue.

**Comment by Tyaaa-aa** [comment]
Feature added in a3cd07b7717b51d0c1dd1b39fd8b1d5c324c20cb
