### ISSUE TITLE
[Feature Request] Add 'clear' button in search text box upon presence of text

### ISSUE THREAD

**Issue by darkcnight** [Tyaaa-aa/Octo-Party-V2#14]
![image](https://github.com/Tyaaa-aa/Octo-Party-V2/assets/82701128/11a12d99-4a1a-4a08-9c52-3c4fecb60bbd)

**Comment by darkcnight** [comment]
clear as in just a 'X'

**Comment by Tyaaa-aa** [comment]
`CTRL + A` then `Backspace`. Hope this helps 👍 @darkcnight
