### ISSUE TITLE
[Feature Request] 'Live' or 'Dynamic' Search function.

### ISSUE THREAD

**Issue by darkcnight** [Tyaaa-aa/Octo-Party-V2#2]
Overview:
Implement a Dynamic Search Function that provides real-time search results as users type their query into the search box. This feature will enhance the user experience by allowing faster and more intuitive navigation through large datasets or lists within the application.

Detailed Description:

1. Functionality:
- As a user begins to type in the search box, the system should instantly filter the visible list or data entries to match the user's input.
- The search should support partial word matching and begin filtering from the first character entered.
- The results should update with each character typed without pressing 'enter' or clicking a search button.

2. Accessibility:
- Ensure the search function is accessible according to WCAG (Web Content Accessibility Guidelines), including keyboard navigability and screen reader support.

3. Fallback Mechanism:
- In cases where no results match the query, display a clear message such "as "No results found" to inform the user.

Gif example so you can get an idea in case reading is too hard.
[![image](https://github.com/Tyaaa-aa/Octo-Party-V2/assets/82701128/3462d1a3-ff83-4e42-a592-479bc3456f86)](https://images.app.goo.gl/XNnts3RZjw2dUc9c6)

**Comment by Tyaaa-aa** [comment]
Feature has been added, you can see it at commit ebdc1edf8d9d070cb045bac815cd337568cf9011 @darkcnight
